/*
 * Generated by tidlc 1.10.6.
 */

#include <stdlib.h>
#include <assert.h>
#include <dlog.h>

#include "rvc_local.h"


#ifdef LOG_TAG
#undef LOG_TAG
#endif

#define LOG_TAG "RPC_PORT_PROXY"

#ifdef _E
#undef _E
#endif

#ifdef _W
#undef _W
#endif

#ifdef _I
#undef _I
#endif

#ifdef _D
#undef _D
#endif

#define _E(fmt, ...) dlog_print(DLOG_ERROR, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)
#define _W(fmt, ...) dlog_print(DLOG_WARN, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)
#define _I(fmt, ...) dlog_print(DLOG_INFO, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)
#define _D(fmt, ...) dlog_print(DLOG_DEBUG, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#ifndef TIDL_VERSION
#define TIDL_VERSION "1.10.6"
#endif

namespace rpc_port {
namespace rvc_local {

namespace proxy {


std::atomic<int> RVCTizenClawService::CallbackBase::seq_num_ { 0 };

RVCTizenClawService::CallbackBase::CallbackBase(int delegate_id, bool once)
    : id_(delegate_id), once_(once) {
  seq_id_ = seq_num_++;
}

int RVCTizenClawService::CallbackBase::GetId() const {
  return id_;
}

int RVCTizenClawService::CallbackBase::GetSeqId() const {
  return seq_id_;
}

bool RVCTizenClawService::CallbackBase::IsOnce() const {
  return once_;
}

std::string RVCTizenClawService::CallbackBase::GetTag() const {
  return std::to_string(id_) + "::" + std::to_string(seq_id_);
}

rpc_port_parcel_h operator << (rpc_port_parcel_h h, const RVCTizenClawService::CallbackBase& cb) {
  rpc_port_parcel_write_int32(h, cb.id_);
  rpc_port_parcel_write_int32(h, cb.seq_id_);
  rpc_port_parcel_write_bool(h, cb.once_);

  return h;
}

rpc_port_parcel_h operator >> (rpc_port_parcel_h h, RVCTizenClawService::CallbackBase& cb) {
  rpc_port_parcel_read_int32(h, &cb.id_);
  rpc_port_parcel_read_int32(h, &cb.seq_id_);
  rpc_port_parcel_read_bool(h, &cb.once_);

  return h;
}

void RVCTizenClawService::ResultCB::OnReceivedEvent(rpc_port_parcel_h parcel) {
  char* param1_raw  = nullptr;
  rpc_port_parcel_read_string(parcel, &param1_raw);
  std::string param1(param1_raw);
  free(param1_raw);

  char* param2_raw  = nullptr;
  rpc_port_parcel_read_string(parcel, &param2_raw);
  std::string param2(param2_raw);
  free(param2_raw);

  OnReceived(std::move(param1), std::move(param2));
}

RVCTizenClawService::RVCTizenClawService(IEventListener* listener, const std::string& target_appid)
    : port_(nullptr), callback_port_(nullptr), proxy_(nullptr),
      listener_(listener), target_appid_(target_appid) {
  int r = rpc_port_proxy_create(&proxy_);

  if (r != RPC_PORT_ERROR_NONE) {
    _E("Failed to create proxy");
    throw InvalidIOException();
  }

  rpc_port_proxy_add_connected_event_cb(proxy_, OnConnectedCB, this);
  rpc_port_proxy_add_disconnected_event_cb(proxy_, OnDisconnectedCB, this);
  rpc_port_proxy_add_rejected_event_cb(proxy_, OnRejectedCB, this);
  rpc_port_proxy_add_received_event_cb(proxy_, OnReceivedCB, this);
}

RVCTizenClawService::~RVCTizenClawService() {
  if (proxy_)
    rpc_port_proxy_destroy(proxy_);
}

void RVCTizenClawService::Connect(bool sync) {
  int ret;
  if (sync)
    ret = rpc_port_proxy_connect_sync(proxy_, target_appid_.c_str(), "RVCTizenClawService");
  else
    ret = rpc_port_proxy_connect(proxy_, target_appid_.c_str(), "RVCTizenClawService");
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to connect RVCTizenClawService");
    switch (ret) {
      case RPC_PORT_ERROR_INVALID_PARAMETER:
        throw InvalidIDException();

      case RPC_PORT_ERROR_IO_ERROR:
        throw InvalidIOException();

      case RPC_PORT_ERROR_PERMISSION_DENIED:
        throw PermissionDeniedException();
    }
  }
}

void RVCTizenClawService::Disconnect() {
  int ret = rpc_port_disconnect(port_);
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to disconnect RVCTizenClawService");
    throw InvalidIDException();
  }
}

void RVCTizenClawService::DisposeCallback(const std::string& tag) {
  for (auto& i : delegate_list_) {
    if (i->GetTag() == tag) {
      delegate_list_.remove(i);
      return;
    }
  }
}

void RVCTizenClawService::ProcessReceivedEvent(rpc_port_parcel_h parcel) {
  int id = 0;
  int seq_id = 0;
  bool once = false;

  rpc_port_parcel_read_int32(parcel, &id);
  rpc_port_parcel_read_int32(parcel, &seq_id);
  rpc_port_parcel_read_bool(parcel, &once);

  for (auto& i : delegate_list_) {
    if (i->GetId() == id && i->GetSeqId() == seq_id) {
      i->OnReceivedEvent(parcel);
      if (i->IsOnce())
        delegate_list_.remove(i);
      break;
    }
  }
}

void RVCTizenClawService::ConsumeCommand(rpc_port_parcel_h* parcel, rpc_port_h port) {
  do {
    rpc_port_parcel_h p;
    int ret = rpc_port_parcel_create_from_port(&p, port);
    int cmd;

    if (ret != 0)
      break;
    rpc_port_parcel_read_int32(p, &cmd);
    if (cmd == static_cast<int>(MethodId::__Result)) {
      *parcel = p;
      return;
    }

    rpc_port_parcel_destroy(p);
    *parcel = nullptr;
  } while (true);
  *parcel = nullptr;
}

void RVCTizenClawService::OnConnectedCB(const char *ep, const char *port_name, rpc_port_h port, void *data) {
  RVCTizenClawService* l = static_cast<RVCTizenClawService*>(data);
  rpc_port_h cb_port;

  l->port_ = port;
  rpc_port_proxy_get_port(l->proxy_, RPC_PORT_PORT_CALLBACK, &cb_port);
  l->callback_port_ = cb_port;
  l->listener_->OnConnected();
}

void RVCTizenClawService::OnDisconnectedCB(const char *ep, const char *port_name, void *data) {
  RVCTizenClawService* l = static_cast<RVCTizenClawService*>(data);
  l->delegate_list_.clear();
  l->listener_->OnDisconnected();
}

void RVCTizenClawService::OnRejectedCB(const char *ep, const char *port_name, void *data) {
  RVCTizenClawService* l = static_cast<RVCTizenClawService*>(data);
  l->listener_->OnRejected();
}

void RVCTizenClawService::OnReceivedCB(const char *ep, const char *port_name, void *data) {
  RVCTizenClawService* l = static_cast<RVCTizenClawService*>(data);
  int cmd;
  rpc_port_parcel_h parcel_received;

  if (rpc_port_parcel_create_from_port(&parcel_received, l->callback_port_) != 0) {
    _E("Failed to create parcel from port");
    return;
  }

  rpc_port_parcel_read_int32(parcel_received, &cmd);
  if (cmd != static_cast<int>(MethodId::__Callback)) {
    rpc_port_parcel_destroy(parcel_received);
    return;
  }

  l->ProcessReceivedEvent(parcel_received);
  rpc_port_parcel_destroy(parcel_received);
}


int RVCTizenClawService::SendCommand(std::string rvcCommand, int mode) {
  if (port_ == nullptr) {
    _E("Not connected");
    throw NotConnectedSocketException();
  }

  rpc_port_parcel_h p;
  rpc_port_parcel_create(&p);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(p, &header_);
  rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  int seq_num_ = -1;
  rpc_port_parcel_header_get_seq_num(header_, &seq_num_);
  rpc_port_parcel_write_int32(p, static_cast<int>(MethodId::SendCommand));
  rpc_port_parcel_write_string(p, rvcCommand.c_str());
  rpc_port_parcel_write_int32(p, mode);

  std::lock_guard<std::recursive_mutex> lock(mutex_);

  // Send
  int r = rpc_port_parcel_send(p, port_);
  if (r != RPC_PORT_ERROR_NONE) {
    _E("Failed to send parcel. result(%d)", r);
    rpc_port_parcel_destroy(p);
    throw InvalidIOException();
  }

  int ret;
  bool done_ = false;
  do {
    rpc_port_parcel_h parcel_received = nullptr;
    // Receive
    ConsumeCommand(&parcel_received, port_);
    if (parcel_received == nullptr) {
      _E("Invalid protocol");
      throw InvalidProtocolException();
    }

    rpc_port_parcel_get_header(parcel_received, &header_);
    char* tag_ = nullptr;
    rpc_port_parcel_header_get_tag(header_, &tag_);
    std::unique_ptr<char, decltype(std::free)*> tag_auto_(tag_, std::free);
    if (tag_ && tag_[0] != '\0') {
      int seq_num_received_ = -1;
      rpc_port_parcel_header_get_seq_num(header_, &seq_num_received_);
      if (seq_num_received_ != seq_num_) {
        _E("Invalid protocol. %d", seq_num_received_);
        rpc_port_parcel_destroy(parcel_received);
        continue;
      }
    }
    done_ = true;

    rpc_port_parcel_read_int32(parcel_received, &ret);

    rpc_port_parcel_destroy(parcel_received);
  } while (!done_);

  rpc_port_parcel_destroy(p);

  return ret;

}
}  // namespace proxy
}  // namespace rvc_local
}  // namespace rpc_port
