/*
 * Generated by tidlc 1.10.6.
 */

#pragma once

#include <bundle.h>
#include <rpc-port-parcel.h>
#include <rpc-port.h>

#include <string>
#include <vector>
#include <memory>
#include <mutex>
#include <list>
#include <atomic>

namespace rpc_port {
namespace rvc_local {
class Bundle final {
 public:
  Bundle() {
    raw_ = bundle_create();
  }

  Bundle(bundle* b) {
    raw_ = b;
  }

  ~Bundle() {
    if (raw_)
      bundle_free(raw_);
  }

  Bundle(Bundle&& b) : raw_(b.raw_) {
    b.raw_ = nullptr;
  }

  Bundle& operator = (Bundle&& b) {
    if (this != &b) {
      if (raw_)
        bundle_free(raw_);

      raw_ = b.raw_;
      b.raw_ = nullptr;
    }
    return *this;
  }

  Bundle(const Bundle& b) : raw_(bundle_dup(b.GetHandle())) {}

  Bundle& operator = (const Bundle& b) {
    if (this != &b) {
      if (raw_)
        bundle_free(raw_);

      raw_ = bundle_dup(b.GetHandle());
    }
    return *this;
  }

  bundle* GetHandle() const {
    return raw_;
  }

 private:
  bundle* raw_;
};

class File final {
 public:
  File() {
  }

  File(std::string filename) {
    filename_ = filename;
  }

  std::string GetFileName() const {
    return filename_;
  }

 private:
  std::string filename_;
};


namespace proxy {

class Exception {};
class NotConnectedSocketException : public Exception {};
class InvalidProtocolException : public Exception {};
class InvalidIOException : public Exception {};
class PermissionDeniedException : public Exception {};
class InvalidIDException : public Exception {};

class RVCTizenClawService {
 public:

  class CallbackBase {
   public:
    CallbackBase(int delegate_id, bool once);
    virtual ~CallbackBase() = default;
    virtual void OnReceivedEvent(rpc_port_parcel_h port) = 0;
    int GetId() const;
    int GetSeqId() const;
    bool IsOnce() const;
    std::string GetTag() const;

   private:
    friend rpc_port_parcel_h operator << (rpc_port_parcel_h h, const CallbackBase& cb);
    friend rpc_port_parcel_h operator >> (rpc_port_parcel_h h, CallbackBase& cb);

    static std::atomic<int> seq_num_;
    int id_;
    int seq_id_;
    bool once_;
  };

  class ResultCB : public CallbackBase {
   public:
    ResultCB(bool once = false)
        : CallbackBase(static_cast<int>(DelegateId::ResultCB), once) {}

    virtual void OnReceived(std::string sender, std::string result) {}

   private:
    void OnReceivedEvent(rpc_port_parcel_h port) override;

  };

  class IEventListener {
   public:
    /// <summary>
    /// This method will be invoked when the client app is connected to the servicece app.
    /// </summary>
    virtual void OnConnected() = 0;

    /// <summary>
    /// This method will be invoked after the client app was disconnected from the servicece app.
    /// </summary>
    virtual void OnDisconnected() = 0;

    /// <summary>
    /// This method will be invoked when the service app rejects the client app.
    /// </summary>
    virtual void OnRejected() = 0;
  };

  /// <summary>
  /// Constructor for this class
  /// </summary>
  /// <param name="listener">The listener for events</param>
  /// <param name="target_appid">The service app ID to connect</param>
  RVCTizenClawService(IEventListener* listener, const std::string& target_appid);

  /// <summary>
  /// Destructor for this class
  /// </summary>
  virtual ~RVCTizenClawService();

  /// <summary>
  /// Connects to the service app.
  /// </summary>
  /// <privilege>http://tizen.org/privilege/appmanager.launch</privilege>
  /// <privilege>http://tizen.org/privilege/datasharing</privilege>
  //  <param name="sync">if true, connects to the service app synchornously</param>
  /// <exception cref="InvalidIDException">
  /// Thrown when the appid to connect is invalid.
  /// </exception>
  /// <exception cref="InvalidIOException">
  /// Thrown when internal I/O error happen.
  /// </exception>
  /// <exception cref="PermissionDeniedException">
  /// Thrown when the permission is denied.
  /// </exception>
  /// <remark> If you want to use this method, you must add privileges.</remark>
  void Connect(bool sync = false);

  /// <summary>
  /// Disconnects from the service app.
  /// </summary>
  /// <exception cref="InvalidIDException">
  /// Thrown when the stub port is invalid.
  /// </exception>
  void Disconnect();

  /// <summary>
  /// Disposes delegate objects in this interface
  /// </summary>
  /// <param name="tag">The tag string from delegate object</param>
  void DisposeCallback(const std::string& tag);

  int SendCommand(std::string rvcCommand, int mode);

 private:
  enum class MethodId : int {
    __Result = 0,
    __Callback = 1,
    SendCommand = 2,

  };

  enum class DelegateId : int {
    ResultCB = 1,

  };
  void ProcessReceivedEvent(rpc_port_parcel_h parcel);
  void ConsumeCommand(rpc_port_parcel_h* parcel, rpc_port_h port);

  static void OnConnectedCB(const char *ep, const char *port_name,
                            rpc_port_h port, void *data);
  static void OnDisconnectedCB(const char *ep, const char *port_name,
                               void *data);
  static void OnRejectedCB(const char *ep, const char *port_name, void *data);
  static void OnReceivedCB(const char *ep, const char *port_name, void *data);

  rpc_port_h port_;
  rpc_port_h callback_port_;
  rpc_port_proxy_h proxy_;
  IEventListener* listener_;
  std::recursive_mutex mutex_;
  std::list<std::unique_ptr<CallbackBase>> delegate_list_;
  std::string target_appid_;
};
}  // namespace proxy
}  // namespace rvc_local
}  // namespace rpc_port
